// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config9_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_V_address0,
        data_V_ce0,
        data_V_q0,
        output_V_address0,
        output_V_ce0,
        output_V_we0,
        output_V_d0,
        output_V_q0
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] data_V_address0;
output   data_V_ce0;
input  [15:0] data_V_q0;
output  [8:0] output_V_address0;
output   output_V_ce0;
output   output_V_we0;
output  [15:0] output_V_d0;
input  [15:0] output_V_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg data_V_ce0;
reg[8:0] output_V_address0;
reg output_V_ce0;
reg output_V_we0;
reg[15:0] output_V_d0;

(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [10:0] linebuffer_V_3_address0;
reg    linebuffer_V_3_ce0;
reg    linebuffer_V_3_we0;
reg   [15:0] linebuffer_V_3_d0;
wire   [15:0] linebuffer_V_3_q0;
wire   [5:0] i0_fu_293_p2;
reg   [5:0] i0_reg_753;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln246_fu_287_p2;
wire   [11:0] zext_ln203_4_fu_304_p1;
reg   [11:0] zext_ln203_4_reg_763;
wire    ap_CS_fsm_state3;
wire   [10:0] zext_ln203_5_fu_308_p1;
reg   [10:0] zext_ln203_5_reg_769;
wire   [7:0] zext_ln203_7_fu_312_p1;
reg   [7:0] zext_ln203_7_reg_774;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln250_fu_325_p2;
wire   [1:0] add_ln255_fu_359_p2;
reg   [1:0] add_ln255_reg_789;
wire   [10:0] add_ln203_2_fu_397_p2;
reg   [10:0] add_ln203_2_reg_799;
wire   [15:0] tmpinput_V_q0;
reg   [15:0] tmp1_V_reg_804;
wire    ap_CS_fsm_state5;
wire   [6:0] zext_ln255_fu_402_p1;
reg   [6:0] zext_ln255_reg_809;
reg   [10:0] linebuffer_V_3_addr_1_reg_815;
reg   [15:0] tmp_V_reg_820;
wire   [4:0] i2_fu_415_p2;
reg   [4:0] i2_reg_828;
wire    ap_CS_fsm_state6;
wire   [11:0] add_ln203_5_fu_446_p2;
reg   [11:0] add_ln203_5_reg_833;
wire   [0:0] icmp_ln258_fu_409_p2;
wire   [1:0] i1_fu_514_p2;
wire   [1:0] i0_1_fu_530_p2;
reg   [1:0] i0_1_reg_851;
wire    ap_CS_fsm_state8;
wire   [6:0] zext_ln192_2_fu_548_p1;
reg   [6:0] zext_ln192_2_reg_856;
wire   [0:0] icmp_ln188_fu_524_p2;
wire   [6:0] add_ln192_fu_552_p2;
reg   [6:0] add_ln192_reg_861;
wire   [1:0] i1_1_fu_564_p2;
reg   [1:0] i1_1_reg_869;
wire    ap_CS_fsm_state9;
wire   [9:0] sub_ln192_fu_594_p2;
reg   [9:0] sub_ln192_reg_874;
wire   [0:0] icmp_ln190_fu_558_p2;
wire   [5:0] i2_2_fu_610_p2;
reg   [5:0] i2_2_reg_883;
wire    ap_CS_fsm_state10;
wire   [9:0] add_ln192_1_fu_625_p2;
reg   [9:0] add_ln192_1_reg_888;
wire   [0:0] icmp_ln191_fu_604_p2;
wire   [1:0] i1_2_fu_667_p2;
reg   [1:0] i1_2_reg_901;
wire    ap_CS_fsm_state12;
wire   [8:0] sub_ln203_fu_693_p2;
reg   [8:0] sub_ln203_reg_906;
wire   [0:0] icmp_ln200_fu_661_p2;
wire   [7:0] zext_ln202_fu_699_p1;
reg   [7:0] zext_ln202_reg_911;
wire   [5:0] i2_1_fu_709_p2;
reg   [5:0] i2_1_reg_919;
wire    ap_CS_fsm_state13;
wire   [8:0] add_ln203_fu_727_p2;
reg   [8:0] add_ln203_reg_924;
wire   [0:0] icmp_ln202_fu_703_p2;
reg   [6:0] tmpinput_V_address0;
reg    tmpinput_V_ce0;
reg    tmpinput_V_we0;
reg   [15:0] tmpinput_V_d0;
reg   [5:0] i0_0_reg_197;
reg   [1:0] i1_0_reg_209;
reg   [4:0] i2_0_reg_221;
wire    ap_CS_fsm_state7;
reg   [1:0] i0_0_i_reg_232;
reg   [1:0] i1_0_i_reg_243;
reg   [5:0] i2_0_i_reg_254;
wire    ap_CS_fsm_state11;
reg   [1:0] i11_0_i_reg_265;
reg   [5:0] i22_0_i_reg_276;
wire    ap_CS_fsm_state14;
wire   [63:0] zext_ln248_fu_299_p1;
wire   [63:0] tmp_97_fu_316_p3;
wire   [63:0] zext_ln252_1_fu_354_p1;
wire   [63:0] zext_ln255_3_fu_386_p1;
wire   [63:0] zext_ln203_8_fu_405_p1;
wire   [63:0] zext_ln203_14_fu_481_p1;
wire   [63:0] zext_ln203_10_fu_509_p1;
wire   [63:0] zext_ln203_12_fu_520_p1;
wire   [63:0] zext_ln192_1_fu_648_p1;
wire   [63:0] zext_ln192_fu_656_p1;
wire   [63:0] zext_ln203_16_fu_741_p1;
wire   [63:0] zext_ln203_fu_746_p1;
wire   [1:0] xor_ln252_fu_331_p2;
wire   [6:0] tmp_99_fu_337_p3;
wire   [7:0] zext_ln252_fu_345_p1;
wire   [7:0] add_ln252_fu_349_p2;
wire   [6:0] tmp_100_fu_365_p3;
wire   [7:0] zext_ln255_2_fu_377_p1;
wire   [7:0] add_ln255_1_fu_381_p2;
wire   [10:0] zext_ln255_1_fu_373_p1;
wire   [10:0] add_ln203_1_fu_391_p2;
wire   [5:0] tmp_103_fu_421_p3;
wire   [6:0] zext_ln203_11_fu_429_p1;
wire   [6:0] add_ln203_4_fu_433_p2;
wire   [11:0] tmp_105_cast_fu_438_p3;
wire   [5:0] tmp_106_fu_451_p3;
wire   [6:0] zext_ln203_13_fu_459_p1;
wire   [6:0] add_ln203_6_fu_463_p2;
wire   [11:0] tmp_108_cast_fu_468_p3;
wire   [11:0] add_ln203_7_fu_476_p2;
wire   [1:0] sub_ln265_fu_486_p2;
wire   [6:0] tmp_102_fu_492_p3;
wire   [7:0] zext_ln203_9_fu_500_p1;
wire   [7:0] add_ln203_3_fu_504_p2;
wire   [0:0] trunc_ln192_fu_536_p1;
wire   [5:0] shl_ln_fu_540_p3;
wire   [8:0] shl_ln192_1_fu_570_p3;
wire   [6:0] shl_ln192_2_fu_582_p3;
wire   [9:0] zext_ln192_3_fu_578_p1;
wire   [9:0] zext_ln192_4_fu_590_p1;
wire   [6:0] zext_ln191_fu_600_p1;
wire   [6:0] add_ln192_2_fu_616_p2;
wire   [9:0] zext_ln192_5_fu_621_p1;
wire   [6:0] add_ln192_3_fu_630_p2;
wire   [9:0] zext_ln192_6_fu_635_p1;
wire   [9:0] add_ln192_4_fu_639_p2;
wire  signed [31:0] sext_ln192_1_fu_644_p1;
wire  signed [31:0] sext_ln192_fu_653_p1;
wire   [6:0] shl_ln203_1_fu_681_p3;
wire   [8:0] shl_ln1_fu_673_p3;
wire   [8:0] zext_ln203_3_fu_689_p1;
wire   [6:0] or_ln_fu_715_p3;
wire   [8:0] zext_ln203_6_fu_723_p1;
wire   [7:0] zext_ln203_15_fu_732_p1;
wire   [7:0] add_ln203_8_fu_736_p2;
reg   [13:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
end

cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config9_s_linebocq #(
    .DataWidth( 16 ),
    .AddressRange( 1152 ),
    .AddressWidth( 11 ))
linebuffer_V_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linebuffer_V_3_address0),
    .ce0(linebuffer_V_3_ce0),
    .we0(linebuffer_V_3_we0),
    .d0(linebuffer_V_3_d0),
    .q0(linebuffer_V_3_q0)
);

cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config5_s_tmpinhbi #(
    .DataWidth( 16 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
tmpinput_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tmpinput_V_address0),
    .ce0(tmpinput_V_ce0),
    .we0(tmpinput_V_we0),
    .d0(tmpinput_V_d0),
    .q0(tmpinput_V_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln246_fu_287_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i0_0_i_reg_232 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln190_fu_558_p2 == 1'd1))) begin
        i0_0_i_reg_232 <= i0_1_reg_851;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i0_0_reg_197 <= 6'd0;
    end else if (((icmp_ln250_fu_325_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        i0_0_reg_197 <= i0_reg_753;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln188_fu_524_p2 == 1'd1))) begin
        i11_0_i_reg_265 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln202_fu_703_p2 == 1'd1))) begin
        i11_0_i_reg_265 <= i1_2_reg_901;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln191_fu_604_p2 == 1'd1))) begin
        i1_0_i_reg_243 <= i1_1_reg_869;
    end else if (((icmp_ln188_fu_524_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        i1_0_i_reg_243 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln258_fu_409_p2 == 1'd1))) begin
        i1_0_reg_209 <= i1_fu_514_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        i1_0_reg_209 <= 2'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        i22_0_i_reg_276 <= i2_1_reg_919;
    end else if (((icmp_ln200_fu_661_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        i22_0_i_reg_276 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln190_fu_558_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        i2_0_i_reg_254 <= 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        i2_0_i_reg_254 <= i2_2_reg_883;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        i2_0_reg_221 <= i2_reg_828;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        i2_0_reg_221 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln191_fu_604_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        add_ln192_1_reg_888 <= add_ln192_1_fu_625_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln188_fu_524_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        add_ln192_reg_861[6 : 5] <= add_ln192_fu_552_p2[6 : 5];
        zext_ln192_2_reg_856[5] <= zext_ln192_2_fu_548_p1[5];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln250_fu_325_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        add_ln203_2_reg_799 <= add_ln203_2_fu_397_p2;
        add_ln255_reg_789 <= add_ln255_fu_359_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln258_fu_409_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        add_ln203_5_reg_833 <= add_ln203_5_fu_446_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln202_fu_703_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        add_ln203_reg_924 <= add_ln203_fu_727_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        i0_1_reg_851 <= i0_1_fu_530_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i0_reg_753 <= i0_fu_293_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        i1_1_reg_869 <= i1_1_fu_564_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        i1_2_reg_901 <= i1_2_fu_667_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        i2_1_reg_919 <= i2_1_fu_709_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        i2_2_reg_883 <= i2_2_fu_610_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        i2_reg_828 <= i2_fu_415_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        linebuffer_V_3_addr_1_reg_815 <= zext_ln203_8_fu_405_p1;
        tmp1_V_reg_804 <= tmpinput_V_q0;
        tmp_V_reg_820 <= linebuffer_V_3_q0;
        zext_ln255_reg_809[1 : 0] <= zext_ln255_fu_402_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln190_fu_558_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        sub_ln192_reg_874[9 : 5] <= sub_ln192_fu_594_p2[9 : 5];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln200_fu_661_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        sub_ln203_reg_906[8 : 5] <= sub_ln203_fu_693_p2[8 : 5];
        zext_ln202_reg_911[6 : 5] <= zext_ln202_fu_699_p1[6 : 5];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        zext_ln203_4_reg_763[5 : 0] <= zext_ln203_4_fu_304_p1[5 : 0];
        zext_ln203_5_reg_769[5 : 0] <= zext_ln203_5_fu_308_p1[5 : 0];
        zext_ln203_7_reg_774[5 : 0] <= zext_ln203_7_fu_312_p1[5 : 0];
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state12) & (icmp_ln200_fu_661_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln200_fu_661_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        data_V_ce0 = 1'b1;
    end else begin
        data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        linebuffer_V_3_address0 = zext_ln203_12_fu_520_p1;
    end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln258_fu_409_p2 == 1'd1))) begin
        linebuffer_V_3_address0 = linebuffer_V_3_addr_1_reg_815;
    end else if (((icmp_ln258_fu_409_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        linebuffer_V_3_address0 = zext_ln203_14_fu_481_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        linebuffer_V_3_address0 = zext_ln255_3_fu_386_p1;
    end else begin
        linebuffer_V_3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln258_fu_409_p2 == 1'd1)) | ((icmp_ln258_fu_409_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        linebuffer_V_3_ce0 = 1'b1;
    end else begin
        linebuffer_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        linebuffer_V_3_d0 = linebuffer_V_3_q0;
    end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln258_fu_409_p2 == 1'd1))) begin
        linebuffer_V_3_d0 = tmp1_V_reg_804;
    end else begin
        linebuffer_V_3_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln258_fu_409_p2 == 1'd1)))) begin
        linebuffer_V_3_we0 = 1'b1;
    end else begin
        linebuffer_V_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        output_V_address0 = zext_ln203_fu_746_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        output_V_address0 = zext_ln192_fu_656_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        output_V_address0 = zext_ln192_1_fu_648_p1;
    end else begin
        output_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        output_V_ce0 = 1'b1;
    end else begin
        output_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        output_V_d0 = tmpinput_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        output_V_d0 = output_V_q0;
    end else begin
        output_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state11))) begin
        output_V_we0 = 1'b1;
    end else begin
        output_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        tmpinput_V_address0 = zext_ln203_16_fu_741_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        tmpinput_V_address0 = zext_ln203_10_fu_509_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        tmpinput_V_address0 = zext_ln252_1_fu_354_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        tmpinput_V_address0 = tmp_97_fu_316_p3;
    end else begin
        tmpinput_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state6))) begin
        tmpinput_V_ce0 = 1'b1;
    end else begin
        tmpinput_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmpinput_V_d0 = tmp_V_reg_820;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        tmpinput_V_d0 = data_V_q0;
    end else begin
        tmpinput_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln258_fu_409_p2 == 1'd1)))) begin
        tmpinput_V_we0 = 1'b1;
    end else begin
        tmpinput_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln246_fu_287_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln250_fu_325_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln258_fu_409_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln188_fu_524_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln190_fu_558_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln191_fu_604_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln200_fu_661_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln202_fu_703_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln192_1_fu_625_p2 = (zext_ln192_5_fu_621_p1 + sub_ln192_reg_874);

assign add_ln192_2_fu_616_p2 = (zext_ln192_2_reg_856 + zext_ln191_fu_600_p1);

assign add_ln192_3_fu_630_p2 = (add_ln192_reg_861 + zext_ln191_fu_600_p1);

assign add_ln192_4_fu_639_p2 = (zext_ln192_6_fu_635_p1 + sub_ln192_reg_874);

assign add_ln192_fu_552_p2 = (7'd32 + zext_ln192_2_fu_548_p1);

assign add_ln203_1_fu_391_p2 = ($signed(zext_ln255_1_fu_373_p1) + $signed(11'd1088));

assign add_ln203_2_fu_397_p2 = (zext_ln203_5_reg_769 + add_ln203_1_fu_391_p2);

assign add_ln203_3_fu_504_p2 = (zext_ln203_7_reg_774 + zext_ln203_9_fu_500_p1);

assign add_ln203_4_fu_433_p2 = (zext_ln255_reg_809 + zext_ln203_11_fu_429_p1);

assign add_ln203_5_fu_446_p2 = (zext_ln203_4_reg_763 + tmp_105_cast_fu_438_p3);

assign add_ln203_6_fu_463_p2 = (zext_ln255_reg_809 + zext_ln203_13_fu_459_p1);

assign add_ln203_7_fu_476_p2 = (zext_ln203_4_reg_763 + tmp_108_cast_fu_468_p3);

assign add_ln203_8_fu_736_p2 = (zext_ln202_reg_911 + zext_ln203_15_fu_732_p1);

assign add_ln203_fu_727_p2 = (sub_ln203_reg_906 + zext_ln203_6_fu_723_p1);

assign add_ln252_fu_349_p2 = (zext_ln203_7_reg_774 + zext_ln252_fu_345_p1);

assign add_ln255_1_fu_381_p2 = (zext_ln203_7_reg_774 + zext_ln255_2_fu_377_p1);

assign add_ln255_fu_359_p2 = ($signed(i1_0_reg_209) + $signed(2'd3));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign data_V_address0 = zext_ln248_fu_299_p1;

assign i0_1_fu_530_p2 = (i0_0_i_reg_232 + 2'd1);

assign i0_fu_293_p2 = (i0_0_reg_197 + 6'd1);

assign i1_1_fu_564_p2 = (i1_0_i_reg_243 + 2'd1);

assign i1_2_fu_667_p2 = (i11_0_i_reg_265 + 2'd1);

assign i1_fu_514_p2 = (i1_0_reg_209 + 2'd1);

assign i2_1_fu_709_p2 = (i22_0_i_reg_276 + 6'd1);

assign i2_2_fu_610_p2 = (i2_0_i_reg_254 + 6'd1);

assign i2_fu_415_p2 = (i2_0_reg_221 + 5'd1);

assign icmp_ln188_fu_524_p2 = ((i0_0_i_reg_232 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln190_fu_558_p2 = ((i1_0_i_reg_243 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln191_fu_604_p2 = ((i2_0_i_reg_254 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln200_fu_661_p2 = ((i11_0_i_reg_265 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln202_fu_703_p2 = ((i22_0_i_reg_276 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln246_fu_287_p2 = ((i0_0_reg_197 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln250_fu_325_p2 = ((i1_0_reg_209 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln258_fu_409_p2 = ((i2_0_reg_221 == 5'd17) ? 1'b1 : 1'b0);

assign or_ln_fu_715_p3 = {{1'd1}, {i22_0_i_reg_276}};

assign sext_ln192_1_fu_644_p1 = $signed(add_ln192_4_fu_639_p2);

assign sext_ln192_fu_653_p1 = $signed(add_ln192_1_reg_888);

assign shl_ln192_1_fu_570_p3 = {{i1_0_i_reg_243}, {7'd0}};

assign shl_ln192_2_fu_582_p3 = {{i1_0_i_reg_243}, {5'd0}};

assign shl_ln1_fu_673_p3 = {{i11_0_i_reg_265}, {7'd0}};

assign shl_ln203_1_fu_681_p3 = {{i11_0_i_reg_265}, {5'd0}};

assign shl_ln_fu_540_p3 = {{trunc_ln192_fu_536_p1}, {5'd0}};

assign sub_ln192_fu_594_p2 = (zext_ln192_3_fu_578_p1 - zext_ln192_4_fu_590_p1);

assign sub_ln203_fu_693_p2 = (shl_ln1_fu_673_p3 - zext_ln203_3_fu_689_p1);

assign sub_ln265_fu_486_p2 = ($signed(2'd2) - $signed(i1_0_reg_209));

assign tmp_100_fu_365_p3 = {{add_ln255_fu_359_p2}, {5'd0}};

assign tmp_102_fu_492_p3 = {{sub_ln265_fu_486_p2}, {5'd0}};

assign tmp_103_fu_421_p3 = {{i2_0_reg_221}, {1'd0}};

assign tmp_105_cast_fu_438_p3 = {{add_ln203_4_fu_433_p2}, {5'd0}};

assign tmp_106_fu_451_p3 = {{i2_fu_415_p2}, {1'd0}};

assign tmp_108_cast_fu_468_p3 = {{add_ln203_6_fu_463_p2}, {5'd0}};

assign tmp_97_fu_316_p3 = {{58'd1}, {i0_0_reg_197}};

assign tmp_99_fu_337_p3 = {{xor_ln252_fu_331_p2}, {5'd0}};

assign trunc_ln192_fu_536_p1 = i0_0_i_reg_232[0:0];

assign xor_ln252_fu_331_p2 = (i1_0_reg_209 ^ 2'd3);

assign zext_ln191_fu_600_p1 = i2_0_i_reg_254;

assign zext_ln192_1_fu_648_p1 = $unsigned(sext_ln192_1_fu_644_p1);

assign zext_ln192_2_fu_548_p1 = shl_ln_fu_540_p3;

assign zext_ln192_3_fu_578_p1 = shl_ln192_1_fu_570_p3;

assign zext_ln192_4_fu_590_p1 = shl_ln192_2_fu_582_p3;

assign zext_ln192_5_fu_621_p1 = add_ln192_2_fu_616_p2;

assign zext_ln192_6_fu_635_p1 = add_ln192_3_fu_630_p2;

assign zext_ln192_fu_656_p1 = $unsigned(sext_ln192_fu_653_p1);

assign zext_ln202_fu_699_p1 = shl_ln203_1_fu_681_p3;

assign zext_ln203_10_fu_509_p1 = add_ln203_3_fu_504_p2;

assign zext_ln203_11_fu_429_p1 = tmp_103_fu_421_p3;

assign zext_ln203_12_fu_520_p1 = add_ln203_5_reg_833;

assign zext_ln203_13_fu_459_p1 = tmp_106_fu_451_p3;

assign zext_ln203_14_fu_481_p1 = add_ln203_7_fu_476_p2;

assign zext_ln203_15_fu_732_p1 = i22_0_i_reg_276;

assign zext_ln203_16_fu_741_p1 = add_ln203_8_fu_736_p2;

assign zext_ln203_3_fu_689_p1 = shl_ln203_1_fu_681_p3;

assign zext_ln203_4_fu_304_p1 = i0_0_reg_197;

assign zext_ln203_5_fu_308_p1 = i0_0_reg_197;

assign zext_ln203_6_fu_723_p1 = or_ln_fu_715_p3;

assign zext_ln203_7_fu_312_p1 = i0_0_reg_197;

assign zext_ln203_8_fu_405_p1 = add_ln203_2_reg_799;

assign zext_ln203_9_fu_500_p1 = tmp_102_fu_492_p3;

assign zext_ln203_fu_746_p1 = add_ln203_reg_924;

assign zext_ln248_fu_299_p1 = i0_0_reg_197;

assign zext_ln252_1_fu_354_p1 = add_ln252_fu_349_p2;

assign zext_ln252_fu_345_p1 = tmp_99_fu_337_p3;

assign zext_ln255_1_fu_373_p1 = tmp_100_fu_365_p3;

assign zext_ln255_2_fu_377_p1 = tmp_100_fu_365_p3;

assign zext_ln255_3_fu_386_p1 = add_ln255_1_fu_381_p2;

assign zext_ln255_fu_402_p1 = add_ln255_reg_789;

always @ (posedge ap_clk) begin
    zext_ln203_4_reg_763[11:6] <= 6'b000000;
    zext_ln203_5_reg_769[10:6] <= 5'b00000;
    zext_ln203_7_reg_774[7:6] <= 2'b00;
    zext_ln255_reg_809[6:2] <= 5'b00000;
    zext_ln192_2_reg_856[4:0] <= 5'b00000;
    zext_ln192_2_reg_856[6] <= 1'b0;
    add_ln192_reg_861[4:0] <= 5'b00000;
    sub_ln192_reg_874[4:0] <= 5'b00000;
    sub_ln203_reg_906[4:0] <= 5'b00000;
    zext_ln202_reg_911[4:0] <= 5'b00000;
    zext_ln202_reg_911[7] <= 1'b0;
end

endmodule //cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config9_s
